# Generated by Django 4.2.5 on 2023-12-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_paquetes_cantidad_remove_paquetes_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetes',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.direcciones'),
        ),
    ]
